### ISSUE TITLE
異體字整理

### ISSUE THREAD

**Issue by chaaklau** [sgalal/rime-cantonese#7]
# 問題簡述

* 八股文詞表採用字形，與香港習慣不同。（例如用「爲」而非「為」）參考：[中州韻說明文件](https://github.com/rime/home/wiki/RimeWithSchemata#八股文)
* 詞表中部份變體（variant），如「靑」（下方為「円」）、户（第一劃為「丶」）、温（右上為「日」而非「囚」）未有收錄，現時做法係用 simplifier 處理地區差異（不轉換，大陸簡體，台灣正體，香港繁體）。
* 即係話，只要詞表入面係按照同一套選字方針，就可以交晒俾 simplifier 處理。
* 實際使用上，例如輸入人名地名時，有時幾個寫法都有必要。因此任何變體最好可以作為「單字」輸入得到。

# 解決方法提案

1. 詞表轉為使用八股文中要求嘅字符（只收錄「牀」，刪去「床」）。暫時只有以下條目需要處理。

```
啤啤床	bi4 bi1 cong4
床單	cong4 daan1
床下底	cong4 haa6 dai2
床褥	cong4 juk2
床笠	cong4 lap1
彈弓床	daan6 gung1 cong4
飛來峰	fei1 loi4 fung1
炕麵包	hong3 min6 baau1
凶神惡煞	hung1 san4 ok3 saat3
撈麵	lou1 min6
淥麵	luk6 min6
麵包	min6 baau1
麵豉	min6 si2
舗床	pou1 cong4
鋪床	pou1 cong4
食貓麵	sik6 maau1 min6
雲吞麵	wan4 tan1 min6
淨麵	zing6 min6
珠穆朗瑪峰	zyu1 muk6 long5 maa5 fung1
```
2. 新增遺漏未有收錄之變體確保單字輸入時可以打出任何漢字字元（包括簡化字）  新增變體排序可以切為 0%，防止非常用變體被用於「無字音詞彙」。需要嘅工作係
	* 增加下表嘅字入去詞表
[香港繁體用字](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/HKVariants.txt)
	* 增加只用於簡體嘅字符，權重定為 0%

# 餘下問題
粵標或其他任何正字法標準，有可能會造出一啲新嘅「異體字關係」（例如「逳」同「郁」會變成異體字），涉及正字法問題可以另外討論。

**Comment by sgalal** [comment]
之前遇到打不出「着火」的問題，是因為生成詞庫時使用的 [繁體字判斷標準](https://github.com/sgalal/rime-cantonese/blob/build/README.md#%E8%A9%9E%E5%BA%AB%E8%A3%BD%E4%BD%9C%E6%B5%81%E7%A8%8B)

```raw
若是 Unicode 基本區漢字
    若能使用 Big5 (cp950) 編碼 -> 是繁體字
    否則 -> 不是繁體字
```

而台灣的「着、著」都寫作「着」，因此「着」被判斷為不是繁體字。

這一部分字可以依據 [台灣繁體用字](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWVariants.txt) 補充。

**Comment by laubonghaudoi** [comment]
所以即係話收錄嘅單字字表需要將所有異體字形都收齊，而詞組就只需要正體？目前我哋嘅碼表中有轉換爲香港同同臺灣字體嘅功能，如果係開啓咗轉換嘅話，噉即係可以打出來嘅單字變少咗？

**Comment by sgalal** [comment]
經過篩選，由於 Big5 繁體字判斷標準產生的問題，只影響下面一些字詞：

```raw
674	痺	痹	bei3
1252	缽	鉢	but3
2059	痴	癡	ci1
2729	才	纔	coi4
2779	床	牀	cong4
2984	潀	潨	cung4
5146	峰	峯	fung1
6295	韁	繮	goeng1
6858	媯	嬀	gwai1
6861	溈	潙	gwai1
7365	嫻	嫺	haan4
7724	核	覈	hat6
8579	凶	兇	hung1
8741	洩	泄	jai6
8782	簷	檐	jam4
9329	睪	睾	jik6
9398	簷	檐	jim4
9682	么	幺	jiu1
9942	湧	涌	jung2
9949	踴	踊	jung2
10465	啟	啓	kai2
11279	群	羣	kwan4
11916	裡	裏	lei5
12043	裡	裏	leoi5
12390	稜	棱	ling4
13720	麵	麪	min6
13821	么	幺	mo1
14720	偽	僞	ngai6
14915	顎	齶	ngok6
15032	鯰	鮎	nim4
16168	晒	曬	saai3
17313	簷	檐	sim4
17559	洩	泄	sit3
18766	抬	擡	toi4
19102	汙	污	waa1
19363	蒍	蔿	wai2
19674	核	覈	wat6
19870	汙	污	wu1
22411	著	着	zoek3
22436	著	着	zoek6
22656	灶	竈	zou3
22851	粽	糉	zung2
22865	眾	衆	zung3
22868	粽	糉	zung3
22982	著	着	zyu3
24064	缽仔糕	鉢仔糕	but3 zai2 gou1
24067	缽仔糕	鉢仔糕	but6 zai2 gou1
24816	才幹	纔幹	coi4 gon3
24817	才學	纔學	coi4 hok6
24824	才能	纔能	coi4 nang4
24828	才華	纔華	coi4 waa4
24829	才智	纔智	coi4 zi3
24830	才智過人	纔智過人	coi4 zi3 gwo3 jan4
28426	核電	覈電	hat6 din6
28427	核心	覈心	hat6 sam1
28457	喉核	喉覈	hau4 wat2
29156	人才	人纔	jan4 coi4
29251	一表人才	一表人纔	jat1 biu2 jan4 coi4
29724	簷蛇	檐蛇	jim4 se2
31104	郎才女貌	郎纔女貌	long4 coi4 neoi5 maau6
32851	晒士	曬士	saai1 si2
32852	晒幸福	曬幸福	saai3 hang6 fuk1
32855	晒命	曬命	saai3 meng6
34782	天才	天纔	tin1 coi4
35082	屋簷	屋檐	uk1 jim4
35087	屋簷	屋檐	uk1 sim4
35333	核突	覈突	wat6 dat6
36723	粽子	糉子	zung2 zi2
```

其中，一些字詞是不應修改的，例如 「才幹」不應修改為「纔幹」；一些字是重複收錄的，也不用修改，例如「晒命」在第 32855 行，「曬命」在第 32856 行。因此這一校對工作需要有人手工完成。

**Comment by sgalal** [comment]
#0908fb76ffa347cc2718d84a83e92ffce0ae6ad5 已經修復解決方法提案中的 (1)；「嗮」和「着火」的問題也在以前的 commit 中修復。

**Comment by leimaau** [comment]
看來有不少異體字要手工調整，想問下爲何「腬」字會失收？這個字應該也包含在unihan中的。

**Comment by chaaklau** [comment]
想問問下面嘅表係邊一個？係咪需要覆核邊一啲唔需要轉換？

> 經過篩選，由於 Big5 繁體字判斷標準產生的問題，只影響下面一些字詞：
> 
> ```
> 674	痺	痹	bei3
> 1252	缽	鉢	but3
> 2059	痴	癡	ci1
> 2729	才	纔	coi4
> 2779	床	牀	cong4
> 2984	潀	潨	cung4
> ```

**Comment by sgalal** [comment]
@chaaklau 

呢個表係根據 [台灣繁體用字](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWVariants.txt)，喺當前嘅 dict 文件中搵出來嘅所有相關條目。需要手工覆核一邊唔需要轉換嘅條目。

**Comment by chaaklau** [comment]
我只可以用香港習慣去講。

**刪除** 
下列項目，右邊寫法會被視為錯字，應該刪除。
（其中「覈 hat6」、「竈」並非錯字，但大部份香港粵語使用者應該無法認讀。）
```
7724	核	覈	hat6
8782	簷	檐	jam4
9398	簷	檐	jim4
9942	湧	涌	jung2
9949	踴	踊	jung2
17313	簷	檐	sim4
19674	核	覈	wat6
22656	灶	竈	zou3
22982	著	着	zyu3
24064	缽仔糕	鉢仔糕	but3 zai2 gou1
24067	缽仔糕	鉢仔糕	but6 zai2 gou1
24816	才幹	纔幹	coi4 gon3
24817	才學	纔學	coi4 hok6
24824	才能	纔能	coi4 nang4
24828	才華	纔華	coi4 waa4
24829	才智	纔智	coi4 zi3
24830	才智過人	纔智過人	coi4 zi3 gwo3 jan4
28426	核電	覈電	hat6 din6
28427	核心	覈心	hat6 sam1
28457	喉核	喉覈	hau4 wat2
29156	人才	人纔	jan4 coi4
29251	一表人才	一表人纔	jat1 biu2 jan4 coi4
29724	簷蛇	檐蛇	jim4 se2
31104	郎才女貌	郎纔女貌	long4 coi4 neoi5 maau6
32851	晒士	曬士	saai1 si2
34782	天才	天纔	tin1 coi4
35082	屋簷	屋檐	uk1 jim4
35087	屋簷	屋檐	uk1 sim4
35333	核突	覈突	wat6 dat6
```

**保留** 
下列項目，左邊寫法會被視為錯字，需要保留轉換規則（即 汙 -> 污） / 或者刪去左邊條目。
```
19102	汙	污	waa1
19870	汙	污	wu1
22411	著	着	zoek3
22436	著	着	zoek6
32852	晒幸福	曬幸福	saai3 hang6 fuk1
32855	晒命	曬命	saai3 meng6
```

**建議刪除**
左右兩字有分工，不應把左邊轉換成右邊。
（「嫻」「嫺」都可以用於人名，「嫺熟」較少用「嫻」；香港民間多用「糉」，小學生學習字詞表用「粽」）
```
2729	才	纔	coi4
2059	痴	癡	ci1
7365	嫻	嫺	haan4
8579	凶	兇	hung1
12390	稜	棱	ling4
16168	晒	曬	saai3
22868	粽	糉	zung3
36723	粽子	糉子	zung2 zi2
```

**可以保留**
以下字形，左右都可以接受，但右邊選字貼近八股文詞庫。

其中以下組合，左邊寫法較常用。
```
674	痺	痹	bei3
1252	缽	鉢	but3
2984	潀	潨	cung4
5146	峰	峯	fung1
6295	韁	繮	goeng1
6858	媯	嬀	gwai1
6861	溈	潙	gwai1
8741	洩	泄	jai6
9329	睪	睾	jik6
9682	么	幺	jiu1
10465	啟	啓	kai2
11279	群	羣	kwan4
13720	麵	麪	min6
13821	么	幺	mo1
14720	偽	僞	ngai6
14915	顎	齶	ngok6
15032	鯰	鮎	nim4
17559	洩	泄	sit3
18766	抬	擡	toi4
19363	蒍	蔿	wai2
22865	眾	衆	zung3
```

以下組合，右邊寫法較常用
```
2779	床	牀	cong4
11916	裡	裏	lei5
12043	裡	裏	leoi5
```

**Comment by laubonghaudoi** [comment]
@chaaklau 
既然「覈」同「竈」唔係錯字，點解要刪除呢？

而最下面嘅嗰個「可以保留」表，我覺得應該統一用八股文字形，噉樣可以儘量交畀自帶嘅opencc轉換來解決，香港人打字可以直接開「香港繁體」，臺灣人開「臺灣正體」，大陸人開「不轉換」。

**Comment by chaaklau** [comment]
等我修改返上一個留言吖。

**Comment by leimaau** [comment]
有啲字係有辨義作用嘅，可以參考[一對多字義辨析表](https://ytenx.org/byohlyuk/KienxPyan)，例如「核」用於「果核」，「覈」用於「覈對」，古今字的範疇，其他有啲就係異體字關係，都可以保留。詞彙部分我意見同 @chaaklau 基本一致。我總結下：保留箭頭方向的，兩個箭頭都有就都保留
```
24064	缽仔糕 => 鉢仔糕	but3 zai2 gou1
24067	缽仔糕 => 鉢仔糕	but6 zai2 gou1
24816	才幹<= 纔幹	coi4 gon3
24817	才學<= 纔學	coi4 hok6
24824	才能<= 纔能	coi4 nang4
24828	才華<= 纔華	coi4 waa4
24829	才智	<= 纔智	coi4 zi3
24830	才智過人<=纔智過人	coi4 zi3 gwo3 jan4
28426	核電<= 覈電	hat6 din6
28427	核心<= 覈心	hat6 sam1
28457	喉核	 喉覈	hau4 wat2（呢個不確定）
29156	人才<= 人纔	jan4 coi4
29251	一表人才 <= 一表人纔	jat1 biu2 jan4 coi4
29724	簷蛇 <=> 檐蛇	jim4 se2
31104	郎才女貌<= 郎纔女貌	long4 coi4 neoi5 maau6
32851	晒士 <=> 曬士	saai1 si2
32852	晒幸福 <=> 曬幸福	saai3 hang6 fuk1
32855	晒命 <=> 曬命	saai3 meng6
34782	天才	<= 天纔	tin1 coi4
35082	屋簷	<=> 屋檐	uk1 jim4
35087	屋簷	<=> 屋檐	uk1 sim4
35333	核突	<= 覈突	wat6 dat6
36723	粽子<=> 糉子	zung2 zi2
```

**Comment by chaaklau** [comment]
> 24064	缽仔糕 => 鉢仔糕	but3 zai2 gou1
> 24067	缽仔糕 => 鉢仔糕	but6 zai2 gou1
呢個左右都保留好唔好？兩個都好常見。

> 28457	喉核<=>喉覈	hau4 wat2（呢個唔確定）
呢個應該刪走右邊合理啲。「覈」應該冇 wat 嘅音。

**Comment by leimaau** [comment]
@chaaklau 

> 24064	缽仔糕 => 鉢仔糕	but3 zai2 gou1
> 24067	缽仔糕 => 鉢仔糕	but6 zai2 gou1
> 呢個左右都保留好唔好？兩個都好常見。
可以兩個都保留，反正opencc自身能夠轉換。

> 28457	喉核<=>喉覈	hau4 wat2（呢個唔確定）
> 呢個應該刪走右邊合理啲。「覈」應該冇 wat 嘅音。
你講得係啱嘅，忘記留意個讀音，多謝提醒，確實應該刪除右邊，「覈」冇wat 嘅音。

**Comment by laubonghaudoi** [comment]
我最新嘅提交修正咗[HKVariants.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/HKVariants.txt)入邊嘅前29個異體字。我首先係將所有詞組入邊嘅用字都統一成八股文標準，然後喺單字表入邊加入香港字形兼將佢哋全部設成0%，除咗個「裊」同「嫋」之外，我兩個都保留並且無加0%。

但係對於呢個文件後面嘅嗰41隻字我就有好多唔確定嘅地方。例如@chaaklau 話「涌」同「踊」係錯字，要保留「湧」同「踴」，但係八股文入邊講嘅係反過來嘅，噉應該係點改至啱？

**Comment by chaaklau** [comment]
喺繁體字入面，「涌」只用於地名，讀 cung1，同「湧」清楚區分；「踴」讀 jung2，而「踊」日常只係見於「舞踊」呢個日語借詞。

**Comment by laubonghaudoi** [comment]
我啱先測試咗一下，如果係打開opencc轉換嘅話，噉所有嘅「涌」字都會轉換成「湧」，噉即係話個opencc轉換有問題？如果係想打香港字形又想打隻「涌」字嘅話，就唔應該打開呢個轉換？

> 喺繁體字入面，「涌」只用於地名，讀 cung1，同「湧」清楚區分（「踴」讀 jung2）；而「踊」日常只係見於「舞踊」呢個日語借詞。

**Comment by chaaklau** [comment]
如果加咗呢行會令到「東涌」「鰂魚涌」「黃泥涌」呢啲香港地名變晒做「湧」，就絕對唔應該打開。

**Comment by laubonghaudoi** [comment]
@chaaklau 如果係噉嘅話，即係話個opencc轉換自己本身就有問題？噉咪大鑊？即係話香港人打字都唔可以淨係靠個香港繁體轉換，因爲噉相當於打部分簡體合併字，要打某些字必須切換返“不轉換”來搵所有字符。

如果係噉，我哋係唔係要將個opencc香港字體轉換嘅字表都改埋先得？

**Comment by chaaklau** [comment]
我啱啱試咗，開咗「香港繁體」真係冇辦法打出嚟。相信係 opencc 都應該改，刪走「涌」「湧」呢一行。
係咪要參考維基百科處理呢堆嘢嘅方法？
https://zh.wikipedia.org/wiki/Wikipedia:%E5%AD%97%E8%AF%8D%E8%BD%AC%E6%8D%A2

**Comment by laubonghaudoi** [comment]
我唔知可唔可以直接pull request到opencc刪咗[呢行](https://github.com/BYVoid/OpenCC/blob/05a2b5c1b684f6f938c4261389cd92289e382c0d/data/dictionary/HKVariants.txt#L30)去，如果得嘅話就最好。仲有我唔知opencc喺呢個碼表入邊嘅轉換係按逐個字符定係詞組搭配來轉換嘅，呢個@sgalal 可能清楚啲？

**Comment by chaaklau** [comment]
唔好意思，我睇漏眼。
opencc 嘅轉換大致冇問題，因為佢哋有另外嘅表去確保一堆詞唔受「涌->湧」嘅變換規則影響。
（當然單獨一個「涌」字，依然係會出問題。）
https://github.com/BYVoid/OpenCC/blob/05a2b5c1b684f6f938c4261389cd92289e382c0d/data/dictionary/HKVariantsPhrases.txt

**Comment by laubonghaudoi** [comment]
@chaaklau 但係我啱啱試咗下，開咗香港繁體之後打/hovv cungv/仲係會出現「河湧」而唔係「河涌」，唔通係我臺機有問題？

而且就算係可以根據呢啲詞組打出個「涌」字，仲係冇辦法單獨打出隻「涌」字，噉即係用戶要切換返個“不轉換”來打隻「涌」字。除咗呢隻字之外嗰個HKVariant.txt入邊仲有無其他噉樣嘅字？

**Comment by leimaau** [comment]
opencc應該可以  [詞彙轉換](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/HKVariantsPhrases.txt) 但我咪太清楚能否使用，如何使用。

**Comment by chaaklau** [comment]
問題係 rime 嘅 filter 可唔可以用到 詞彙轉換。（好似唔得）
我覺得既然 rime-cantonese 詞表係繁體做底，涌 字嘅轉換規則冇需要，應該刪除。但係如果張 list 係直接用
opencc，噉就要諗諗辦法。

**Comment by laubonghaudoi** [comment]
> 問題係 rime 嘅 filter 可唔可以用到 詞彙轉換。（好似唔得） 我覺得既然 rime-cantonese 詞表係繁體做底，涌 字嘅轉換規則冇需要，應該刪除。但係如果張 list 係直接用 opencc，噉就要諗諗辦法。

唔係好睇得明呢段話，張list直接用opencc係咩意思？我唔清楚Rime碼表可唔可以啓用opencc嘅詞組轉換，要返去睇下文檔。

**Comment by sgalal** [comment]
我提交了兩個 commit 5ffcab08c735440eacce67f06d34a4cff8d3ebf4, 6a1fdccc8f1871c5d75492c5060dd20a2a066f91，可以修復「涌、湧」的問題。部署前需要將 [`/opencc/t2hkp.json`](https://github.com/sgalal/rime-cantonese/blob/6a1fdccc8f1871c5d75492c5060dd20a2a066f91/opencc/t2hkp.json) 置於【小狼毫】程序文件夾的 `opencc` 文件夾中。

![東涌](https://user-images.githubusercontent.com/32255369/67613029-36c09500-f7db-11e9-9ffa-60a3faa202fb.png)

![湧起](https://user-images.githubusercontent.com/32255369/67613031-3d4f0c80-f7db-11e9-88d9-cfc3ddaadef6.png)

**Comment by sgalal** [comment]
Related:

https://github.com/BYVoid/OpenCC/pull/69

https://github.com/BYVoid/OpenCC/issues/142

**Comment by sgalal** [comment]
因為八股文詞庫用「涌」代表「湧起」，所以應將粵拼詞庫中含有「湧」的詞語改為「涌」，並將單字「湧」記為 0%

**Comment by sgalal** [comment]
> 看來有不少異體字要手工調整，想問下爲何「腬」字會失收？這個字應該也包含在unihan中的。

這是一個問題，因為這個字在基本區，但是沒有 Big5 編碼，被判斷為非繁體字

**Comment by laubonghaudoi** [comment]
我啱先更新基本上修復咗個異體字問題，唔該覺得測試下得唔得，主要係測試幾個香港字形單字同埋個「涌」「 湧」嘅問題。

**Comment by sgalal** [comment]
> @sgalal 而家有個問題，就係即使個問題解決咗，都仲係要靠自己手動複製`t2hkp.json`文件，操作好麻煩。所以可唔可以直接向opencc庫修改，一勞永逸？

我提交了一個 Pull Request: https://github.com/BYVoid/OpenCC/pull/351，但是 OpenCC 已經有一百多個 issue 沒有處理了。在 merge 以前我們只能暫時手動複製 `t2hkp.json` 文件，希望全平臺的自動化安裝都做好以後這個問題可以一併解決。

另外我上面說：

> 因為八股文詞庫用「涌」代表「湧起」，所以應將粵拼詞庫中含有「湧」的詞語改為「涌」，並將單字「湧」記為 0%

經過嘗試，我發現這並不是一個很好的方法，因爲這樣就只能在 `HKVariantsPhrases.txt` 中枚舉每種情況：「蠔涌、西涌、鰂魚涌、麻涌、黎涌、洶湧、潮湧、泉湧、翻湧、風起潮湧、風起雲湧、蜂湧、洶湧澎湃……」。

我認爲可以這樣解決：保持我們對詞庫的修改不變（即區分「湧、涌」），同時在 HKVariants 中刪除「湧」字的轉換規則。

**Comment by sgalal** [comment]
但是這樣仍然有問題，就是現在的詞庫（區分「湧、涌」）和八股文詞庫（全部用「涌」）不兼容，導致八股文詞庫中含有「涌」的詞語不能參與造詞。

**Comment by chaaklau** [comment]
> 我認爲可以這樣解決：保持我們對詞庫的修改不變（即區分「湧、涌」），同時在 HKVariants 中刪除「湧」字的轉換規則。
> 但是這樣仍然有問題，就是現在的詞庫（區分「湧、涌」）和八股文詞庫（全部用「涌」）不兼容，導致八股文詞庫中含有「涌」的詞語不能參與造詞。

即係話八股文入面有「涌」嘅詞，如果寫法應該係「湧」，我哋就要喺 rime-cantonese 詞庫手動添加，係嗎？

八股文詞庫入面所有含有「涌」字元嘅詞語，依然會按頻率顯示（可惜權重係「非負整數」，個別詞表冇辦法取消八股文詞庫嘅條目），例如打 jung2 hei2 會同時顯示「湧起」同「涌起」。

**Comment by laubonghaudoi** [comment]
@sgalal 如果我哋刪除HKVarients中嘅「湧」轉「涌」規則，噉樣即係要等opencc merge咗我哋嘅pull request先得，等到嗰陣蚊都瞓。

八股文詞庫唔兼容呢個應該唔係咩大問題？雖然「涌」字唔參預組詞，但係我哋仲係可以靠單字打/cung/打出隻「涌」字來，係唔係？

**Comment by sgalal** [comment]
我啱啱提交咗一個 Pull Request https://github.com/sgalal/rime-cantonese/pull/9 ，實現喺香港繁體模式下，輸入 cung1 只出現「涌」，輸入 jung2 只出現「湧」。

> 即係話八股文入面有「涌」嘅詞，如果寫法應該係「湧」，我哋就要喺 rime-cantonese 詞庫手動添加，係嗎？

係，否則因為唔自動組詞，呢啲詞打唔出

> 如果我哋刪除HKVarients中嘅「湧」轉「涌」規則，噉樣即係要等opencc merge咗我哋嘅pull request先得，等到嗰陣蚊都瞓。

唔紧要，我哋可以手动將修改過的 OpenCC 文件複製到 OpenCC 文件夾

而家需要複製嘅文件係 `/opencc/HKVariantsCantonese.txt` 同 `/opencc/t2hkcanto.json`。

`HKVariantsCantonese.txt` 同原來 `HKVariants.txt` 嘅區別係，`HKVariantsCantonese.txt` 冇「涌」字嘅轉換規則。

> 八股文詞庫唔兼容呢個應該唔係咩大問題？

我都覺得應該唔係咩大問題。

> 雖然「涌」字唔參預組詞，但係我哋仲係可以靠單字打/cung/打出隻「涌」字來，係唔係？

原來喺香港繁體模式下打唔出來，我嘅 Pull Request 即係解決呢個問題。

**Comment by laubonghaudoi** [comment]
@sgalal  我喺度諗，係唔係直接向Rime引擎pr會更加方便？而家噉樣仲係要手工複製文件好麻煩，尤其喺手機更加唔方便，如果可以直接Rime預裝就好了。

**Comment by sgalal** [comment]
「湧」、「涌」的問題已經在 https://github.com/BYVoid/OpenCC/pull/387 中完全修復了，OpenCC 現在將這兩個字區別對待。
