### ISSUE TITLE
是否應該取消教院式聲母簡拼支持

### ISSUE THREAD

**Issue by laubonghaudoi** [sgalal/rime-cantonese#8]
https://github.com/sgalal/rime-cantonese/blob/a6bad94fcf8d7037e156065c57c154ba892a27df/jyut6ping3.schema.yaml#L99
我喺打「發聲」呢個詞嗰陣發覺而家嘅碼表會將/faat sing/識別成/faa tsing/，因而輸出「花青」。我哋有無必要默認將呢幾行代碼註釋咗佢？默認嚴格按照粵拼規則來輸入。

**Comment by sgalal** [comment]
可以再新建一個 schema 支援教院式拼音

**Comment by laubonghaudoi** [comment]
噉我係唔係應該將第97-101行都刪嗮？

**Comment by sgalal** [comment]
係，可以新建個教院式拼音嘅 schema，並喺 README 中説明
